'use strict';
// sql template autogenerated by gen-db-migrates

var async = require('async')
var dbm;
var type;
var seed;

/**
* We receive the dbmigrate dependency from dbmigrate initially.
* This enables us to not have to rely on NODE_PATH.
*/
exports.setup = function(options, seedLink) {
  dbm = options.dbmigrate;
  type = dbm.dataType;
  seed = seedLink;
};

exports.up = function (db, callback) {
  async.series([
    (cb) => db.createTable('module', {
    columns: {
    "id": {
        "type": "serial",
        "autoIncrement": true
    },
    "name": {
        "type": "text"
    },
    "appId": {
        "type": "text",
        "unique": true,
        "primaryKey": true
    },
    "version": {
        "type": "text"
    },
    "enable": {
        "type": "boolean"
    },
    "migrationsCount": {
        "type": "real"
    },
    "migrationsResult": {
        "type": "text"
    },
    "isDeleted": {
        "type": "boolean"
    },
    "directoryName": {
        "type": "text"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),
(cb) => db.createTable('settings', {
    columns: {
    "id": {
        "type": "serial",
        "autoIncrement": true,
        "primaryKey": true
    },
    "key": {
        "type": "text",
        "unique": true
    },
    "name": {
        "type": "text"
    },
    "description": {
        "type": "text"
    },
    "tooltip": {
        "type": "text"
    },
    "value": {
        "type": "json"
    },
    "defaultValue": {
        "type": "json"
    },
    "type": {
        "type": "text"
    },
    "jsonSchema": {
        "type": "json"
    },
    "uiSchema": {
        "type": "json"
    },
    "readOnly": {
        "type": "boolean"
    },
    "module": {
        "type": "text"
    },
    "isRequired": {
        "type": "boolean"
    },
    "createdAt": {
        "type": "bigint"
    },
    "updatedAt": {
        "type": "bigint"
    }
},
    ifNotExists: true
  }, cb),

  ], callback);
}

exports.down = function(db) {
  return null;
};

exports._meta = {
  "version": 1
};
